// Generated by node scripts/generate-tokens.mjs from specification/tokens.
// Do not edit this file directly. Update the DTCG source and regenerate it.

package beez.design.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * BEEZ default schemes generated from the DTCG token source.
 */
public object BeezTokenSchemes {
    public val light: BeezTokenScheme = BeezTokenScheme(
        colors = lightColors(),
        typography = defaultTypography(),
        spacing = defaultSpacing(),
        shapes = defaultShapes(),
        elevation = defaultElevation(),
        motion = defaultMotion(),
    )

    public val dark: BeezTokenScheme = light.copy(
        colors = darkColors(),
    )
}

private fun lightColors(): BeezColorScheme = BeezColorScheme(
    backgroundBrand = Color(0xFF9A3412),
    backgroundNeutral = Color(0xFFFFFFFF),
    backgroundCritical = Color(0xFFBA1A1A),
    foregroundPrimary = Color(0xFF1C1B1F),
    foregroundSecondary = Color(0xFF625B71),
    foregroundOnBrand = Color(0xFFFFFFFF),
    foregroundCritical = Color(0xFFBA1A1A),
    strokeNeutral = Color(0xFF79747E),
    strokeFocus = Color(0xFF9A3412),
    strokeCritical = Color(0xFFBA1A1A),
    overlayScrim = Color(0x99000000),
)

private fun darkColors(): BeezColorScheme = BeezColorScheme(
    backgroundBrand = Color(0xFFFFB36B),
    backgroundNeutral = Color(0xFF1C1B1F),
    backgroundCritical = Color(0xFFFFB4AB),
    foregroundPrimary = Color(0xFFE6E1E5),
    foregroundSecondary = Color(0xFFCAC4D0),
    foregroundOnBrand = Color(0xFF3B1800),
    foregroundCritical = Color(0xFFFFB4AB),
    strokeNeutral = Color(0xFF938F99),
    strokeFocus = Color(0xFFFFB36B),
    strokeCritical = Color(0xFFFFB4AB),
    overlayScrim = Color(0x99000000),
)

private fun defaultTypography(): BeezTypographyScheme = BeezTypographyScheme(
    display = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 36.sp,
        lineHeight = 44.sp,
        fontWeight = FontWeight.Bold,
    ),
    screenTitle = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 28.sp,
        lineHeight = 36.sp,
        fontWeight = FontWeight.Bold,
    ),
    sectionTitle = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 20.sp,
        lineHeight = 28.sp,
        fontWeight = FontWeight.SemiBold,
    ),
    body = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 16.sp,
        lineHeight = 24.sp,
        fontWeight = FontWeight.Normal,
    ),
    label = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        fontWeight = FontWeight.Medium,
    ),
    caption = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        fontWeight = FontWeight.Normal,
    ),
)

private fun defaultSpacing(): BeezSpacingScheme = BeezSpacingScheme(
    minimumTouchTarget = 48.dp,
    screenGutter = 24.dp,
    screenSectionGap = 32.dp,
    contentInlineGap = 8.dp,
    contentStackGap = 16.dp,
    controlContentGap = 8.dp,
    controlCompactHeight = 40.dp,
    controlDefaultHeight = 48.dp,
    controlComfortableHeight = 56.dp,
    controlCompactHorizontalInset = 12.dp,
    controlDefaultHorizontalInset = 16.dp,
    controlComfortableHorizontalInset = 20.dp,
    controlCompactVerticalInset = 8.dp,
    controlDefaultVerticalInset = 12.dp,
    controlComfortableVerticalInset = 16.dp,
)

private fun defaultShapes(): BeezShapeScheme = BeezShapeScheme(
    controlRadius = 12.dp,
    containerRadius = 12.dp,
    overlayRadius = 24.dp,
    roundRadius = 999.dp,
)

private fun defaultElevation(): BeezElevationScheme = BeezElevationScheme(
    level0 = 0.dp,
    level1 = 1.dp,
    level2 = 3.dp,
    raised = 1.dp,
    floating = 3.dp,
    overlay = 8.dp,
)

private fun defaultMotion(): BeezMotionScheme = BeezMotionScheme(
    instantMillis = 0,
    fastMillis = 120,
    moderateMillis = 200,
    slowMillis = 300,
)
