// Generated by node scripts/generate-tokens.mjs from specification/tokens/themes/test-brand.theme.json.
// Do not edit this file directly. Update the DTCG source and regenerate it.

package beez.design.catalog

import androidx.compose.ui.graphics.Color
import beez.design.tokens.BeezTokenScheme

internal fun BeezTokenScheme.withCatalogTestBrand(): BeezTokenScheme = copy(
    colors = colors.copy(
        backgroundBrand = Color(0xFF1769AB),
        foregroundOnBrand = Color(0xFFFFFFFF),
        strokeFocus = Color(0xFF1769AB),
    ),
)
